name: kawaii_vision
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  rflutter_alert: ^2.0.7
  webview_flutter: ^4.9.0

#  using serializable to have more features
#  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

#    for networkImage testing
  network_image_mock: ^2.1.1

#  Taking JSON input from api and serialize(decode) it industry standard
#  json_serializable: ^1.0.0

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true


  assets:
     - assets/images/anabella.jpg
     - assets/images/frame3.png
     - assets/images/img2.jpg



  fonts:
    - family: Creepster
      fonts:
        - asset: assets/fonts/Creepster-Regular.ttf

    - family: Nosifer
      fonts:
        - asset: assets/fonts/Nosifer-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Italic-VariableFont_wght.ttf
          weight: 600

    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-VariableFont_wght.ttf
          weight: 400

